from __future__ import annotations
import enum


class PostType(enum.StrEnum):
    BIGINT = "BIGINT"
    BIGSERIAL = "BIGSERIAL"
    BIT = "BIT"
    BIT_VATYING = "BIT VATYING"
    BOOLEAN = "BOOLEAN"
    BOX = "BOX"
    BYTEA = "BYTEA"
    BYNARY = "BYNARY"
    CHARACTER = "CHARACTER"
    CHARACTER_VARYING = "CHARACTER VARYING"
    CIDR = "CIDR"
    CIRCLE = "CIRCLE"
    DATE = "DATE"
    DOUBLE_PRECISION = "DOUBLE PRECISION"
    INET = "INET"
    INTEGER = "INTEGER"
    INTERVAL = "INTERVAL"
    JSON = "JSON"
    JSONB = "JSONB"
    LINE = "LINE"
    LSEG = "LSEG"
    MACADDR = "MACADDR"
    MACADDR8 = "MACADDR8"
    MONEY = "MONEY"
    NUMERIC = "NUMERIC"
    PATH = "PATH"
    PG_LSN = "PG_LSN"
    PG_SNAPSHOT = "PG_SNAPSHOT"
    POINT = "POINT"
    POLYGON = "POLYGON"
    REAL = "REAL"
    SMALLINT = "SMALLINT"
    SMALLSERIAL = "SMALLSERIAL"
    SERIAL = "SERIAL"
    TEXT = "TEXT"
    TIME = "TIME"
    TIMESTAMP = "TIMESTAMP"
    TSQUERY = "TSQUERY"
    TSVECTOR = "TSVECTOR"
    TXID_SNAPSHOT = "TXID_SNAPSHOT"
    UUID = "UUID"
    XML = "XML"

    @classmethod
    def get(cls, value: str) -> PostType:
        return cls(value.upper())
